PLAYER_TOTAL_LIFE = 100
MAX_POTIONS_TO_CARRY = 3
STARTING_PLAYER_POTION_NUM = 1

FIGHTER_DAMAGE_BONUS = 5
FIGHTER_SPEED_DECREMENT = 5
FIGHTER_POWER_BONUS = 1
FIGHTER_POTION_CARRY_BONUS = 1

THIEF_SPEED_BONUS = 5
THIEF_POWER_DECREMENT = 5
THIEF_GOLD_BONUS = 5

WIZARD_POTION_CARRY_DECREMENT = 1

LIFE_POTION_GOLD_VALUE = 30
LIFE_POTION_RETURN_LIFE = 10

MONSTER_BASE_LIFE = 70

GOBLIN_SPEED_BONUS = 1
GOBLIN_POWER_DECREMENT = 1
GOBLIN_GOLD_BONUS = 50

ORK_POWER_BONUS = 1
ORK_SPEED_DECREMENT = 1
ORK_LIFE = 150

MAZE_CHANCE_GEN_MONSTER = 0.8
MAZE_MIN_ROOM_NUM = 4
MAZE_MIN_MONSTER_NUM = 3
MAZE_POTION_ROOM_PROB = 0.5
